# Generated by Django 2.0.2 on 2018-07-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebookAccount',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='goodreadsAccount',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='googleAccount',
            field=models.TextField(null=True),
        ),
    ]
