# Generated by Django 2.0.2 on 2018-07-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180702_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twitterAccount',
            field=models.TextField(null=True),
        ),
    ]
