# Generated by Django 2.0.2 on 2018-07-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_resetpasswordtokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emailNotifications',
            field=models.BooleanField(default=True),
        ),
    ]
