# Generated by Django 2.0.2 on 2018-07-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_emailnotifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Junk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField(null=True)),
                ('data1', models.TextField(null=True)),
                ('data2', models.TextField(null=True)),
                ('data3', models.TextField(null=True)),
                ('data4', models.TextField(null=True)),
                ('data5', models.TextField(null=True)),
                ('data6', models.TextField(null=True)),
            ],
        ),
    ]
