# Generated by Django 2.0.2 on 2018-06-17 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('author', models.TextField()),
                ('isbn', models.TextField()),
                ('photo', models.TextField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('downVotes', models.ManyToManyField(related_name='downVotes', to=settings.AUTH_USER_MODEL)),
                ('upVotes', models.ManyToManyField(related_name='upVotes', to=settings.AUTH_USER_MODEL)),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
