# Generated by Django 2.0.2 on 2018-06-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='photo',
            field=models.TextField(null=True),
        ),
    ]
