# Generated by Django 2.0.2 on 2018-07-18 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180620_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='isbn',
            new_name='bookID',
        ),
    ]
