# Generated by Django 2.0.2 on 2018-06-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180618_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='textSnippet',
            field=models.TextField(null=True),
        ),
    ]
