# Generated by Django 2.0.2 on 2018-06-19 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_books_textsnippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='photo',
            new_name='image',
        ),
    ]
