# Generated by Django 2.0.2 on 2018-06-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180620_1754'),
        ('groups', '0002_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='readBookList',
            field=models.ManyToManyField(related_name='readBookList', to='books.Books'),
        ),
    ]
