# Generated by Django 2.0.2 on 2018-06-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_readbooklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='currentBookDeadline',
            field=models.DateField(null=True),
        ),
    ]
