# Generated by Django 2.0.2 on 2018-06-28 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0005_remove_group_passphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='pendingApprovals',
            field=models.ManyToManyField(related_name='pendingApprovals', to=settings.AUTH_USER_MODEL),
        ),
    ]
